### ISSUE TITLE
Google Colabでqulacs-gpuをインストールできない。

### ISSUE THREAD

**Issue by TenninYan** [qulacs/qulacs#119]
pip install -v -i https://test.pypi.org/simple/ qulacs-gpu

```
Created temporary directory: /tmp/pip-ephem-wheel-cache-os8e7cx0
Created temporary directory: /tmp/pip-req-tracker-s78ktjmr
Created requirements tracker '/tmp/pip-req-tracker-s78ktjmr'
Created temporary directory: /tmp/pip-install-sm_za7pb
Looking in indexes: https://test.pypi.org/simple/
Collecting qulacs-gpu
  1 location(s) to search for versions of qulacs-gpu:
  * https://test.pypi.org/simple/qulacs-gpu/
  Getting page https://test.pypi.org/simple/qulacs-gpu/
  Looking up "https://test.pypi.org/simple/qulacs-gpu/" in the cache
  Request header has "max_age" as 0, cache bypassed
  Starting new HTTPS connection (1): test.pypi.org:443
  https://test.pypi.org:443 "GET /simple/qulacs-gpu/ HTTP/1.1" 304 0
  Analyzing links from page https://test.pypi.org/simple/qulacs-gpu/
    Found link https://test-files.pythonhosted.org/packages/2b/f6/ba47e622de59ce13b5cbb5fbcfcc38d7e37848d127c9bfdb5f23996364f4/Qulacs-GPU-0.1.0a0.tar.gz#sha256=8b2584d1836406ce4890210de902dc03b2887a0af53b7ad9333b217e3ba409fb (from https://test.pypi.org/simple/qulacs-gpu/), version: 0.1.0a0
    Found link https://test-files.pythonhosted.org/packages/57/96/829b4c53edae8b39ed709f40ce75d8cef643608c522996a855c366d50f54/Qulacs-GPU-0.1.0b0.tar.gz#sha256=2c1e8ef740a63f317a08b325217370dbfd64e5c1838ae622eb9f1affaea40f78 (from https://test.pypi.org/simple/qulacs-gpu/), version: 0.1.0b0
    Found link https://test-files.pythonhosted.org/packages/26/3d/faff84c6a21014a85b1c200ac2ccf19cfaa7ecc29a5a2d0a88860d519ad1/Qulacs-GPU-0.1.0rc0.tar.gz#sha256=ddddadf3c6a4c150d0f67a292eca2bec8511f6ca51e86c70e35853223feee98f (from https://test.pypi.org/simple/qulacs-gpu/), version: 0.1.0rc0
    Found link https://test-files.pythonhosted.org/packages/62/c5/a30b248af1ae05b68a9f236de4fbb4ec0d4b91ee639522ca634cd117b298/Qulacs-GPU-0.1.0.tar.gz#sha256=67bc62291b10c83d848227a14173d7b06dc2a965d165743b7e4acaa17bdb2fb5 (from https://test.pypi.org/simple/qulacs-gpu/), version: 0.1.0
    Found link https://test-files.pythonhosted.org/packages/2f/df/2722fbe7a945c68dfa61f6c707c41e91f6c5bb5e1fbba713e9bcd777b1b3/Qulacs-GPU-0.1.2.tar.gz#sha256=047dcd4e4053ab85c3561b896ce3625868004663e61ab9809743d578a8f45ccb (from https://test.pypi.org/simple/qulacs-gpu/), version: 0.1.2
  Using version 0.1.2 (newest of versions: 0.1.0, 0.1.2)
  Created temporary directory: /tmp/pip-unpack-4g76uswu
  Looking up "https://test-files.pythonhosted.org/packages/2f/df/2722fbe7a945c68dfa61f6c707c41e91f6c5bb5e1fbba713e9bcd777b1b3/Qulacs-GPU-0.1.2.tar.gz" in the cache
  Current age based on date: 126
  Starting new HTTPS connection (1): test-files.pythonhosted.org:443
  https://test-files.pythonhosted.org:443 "GET /packages/2f/df/2722fbe7a945c68dfa61f6c707c41e91f6c5bb5e1fbba713e9bcd777b1b3/Qulacs-GPU-0.1.2.tar.gz HTTP/1.1" 304 0
  Using cached https://test-files.pythonhosted.org/packages/2f/df/2722fbe7a945c68dfa61f6c707c41e91f6c5bb5e1fbba713e9bcd777b1b3/Qulacs-GPU-0.1.2.tar.gz
  Downloading from URL https://test-files.pythonhosted.org/packages/2f/df/2722fbe7a945c68dfa61f6c707c41e91f6c5bb5e1fbba713e9bcd777b1b3/Qulacs-GPU-0.1.2.tar.gz#sha256=047dcd4e4053ab85c3561b896ce3625868004663e61ab9809743d578a8f45ccb (from https://test.pypi.org/simple/qulacs-gpu/)
  Added qulacs-gpu from https://test-files.pythonhosted.org/packages/2f/df/2722fbe7a945c68dfa61f6c707c41e91f6c5bb5e1fbba713e9bcd777b1b3/Qulacs-GPU-0.1.2.tar.gz#sha256=047dcd4e4053ab85c3561b896ce3625868004663e61ab9809743d578a8f45ccb to build tracker '/tmp/pip-req-tracker-s78ktjmr'
    Running setup.py (path:/tmp/pip-install-sm_za7pb/qulacs-gpu/setup.py) egg_info for package qulacs-gpu
    Running command python setup.py egg_info
    running egg_info
    creating pip-egg-info/Qulacs_GPU.egg-info
    writing pip-egg-info/Qulacs_GPU.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/Qulacs_GPU.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/Qulacs_GPU.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/Qulacs_GPU.egg-info/SOURCES.txt'
    reading manifest file 'pip-egg-info/Qulacs_GPU.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pip-egg-info/Qulacs_GPU.egg-info/SOURCES.txt'
  Source in /tmp/pip-install-sm_za7pb/qulacs-gpu has version 0.1.2, which satisfies requirement qulacs-gpu from https://test-files.pythonhosted.org/packages/2f/df/2722fbe7a945c68dfa61f6c707c41e91f6c5bb5e1fbba713e9bcd777b1b3/Qulacs-GPU-0.1.2.tar.gz#sha256=047dcd4e4053ab85c3561b896ce3625868004663e61ab9809743d578a8f45ccb
  Removed qulacs-gpu from https://test-files.pythonhosted.org/packages/2f/df/2722fbe7a945c68dfa61f6c707c41e91f6c5bb5e1fbba713e9bcd777b1b3/Qulacs-GPU-0.1.2.tar.gz#sha256=047dcd4e4053ab85c3561b896ce3625868004663e61ab9809743d578a8f45ccb from build tracker '/tmp/pip-req-tracker-s78ktjmr'
Building wheels for collected packages: qulacs-gpu
  Created temporary directory: /tmp/pip-wheel-n_s91q8i
  Building wheel for qulacs-gpu (setup.py) ...   Destination directory: /tmp/pip-wheel-n_s91q8i
  Running command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-sm_za7pb/qulacs-gpu/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-n_s91q8i --python-tag cp36
  running bdist_wheel
  running build
  running build_ext
  -- The C compiler identification is GNU 7.3.0
  -- The CXX compiler identification is GNU 7.3.0
  -- Check for working C compiler: /usr/bin/gcc
  -- Check for working C compiler: /usr/bin/gcc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /usr/bin/g++
  -- Check for working CXX compiler: /usr/bin/g++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- USE_OMP = Yes
  -- USE_GPU = Yes
  -- USE_TEST = Yes
  -- USE_PYTHON = Yes
  -- Fetch googletest for C++ testing
  -- Found PythonInterp: /usr/bin/python3 (found version "3.6.7")
  -- Looking for pthread.h
  -- Looking for pthread.h - found
  -- Looking for pthread_create
  -- Looking for pthread_create - not found
  -- Check if compiler accepts -pthread
  -- Check if compiler accepts -pthread - yes
  -- Found Threads: TRUE
  -- Fetch pybind11 for python-binding
  -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so
  -- Performing Test HAS_CPP14_FLAG
  -- Performing Test HAS_CPP14_FLAG - Success
  -- pybind11 v2.2.4
  -- Install from pip
  -- OUTDIR = /tmp/pip-install-sm_za7pb/qulacs-gpu/build/lib.linux-x86_64-3.6
  -- CMAKE_SYSTEM_NAME = Linux
  -- CMAKE_C_COMPILER = /usr/bin/gcc
  -- CMAKE_CXX_COMPILER = /usr/bin/g++
  -- USE_OMP = Yes
  -- CMAKE_BUILD_TYPE = Release
  -- CMAKE_CXX_FLAGS = -DVERSION_INFO=\"0.1.2\" -std=gnu++11 -pthread -fext-numeric-literals -fopenmp -fPIC
  -- CMAKE_CXX_FLAGS_DEBUG = -g
  -- CMAKE_CXX_FLAGS_RELEASE = -O3 -DNDEBUG -mtune=native -march=native -mfpmath=both
  -- Found CUDA: /usr/local/cuda (found version "10.0")
  -- CUDA --
  Version: 10.0
  Library: /usr/lib/x86_64-linux-gnu/libcuda.so
  Runtime: /usr/local/cuda/lib64/libcudart.so
  Flag:
  -- Performing Test HAS_FLTO
  -- Performing Test HAS_FLTO - Success
  -- LTO enabled
  CMake Warning (dev) at python/CMakeLists.txt:58 (target_link_libraries):
    Policy CMP0023 is not set: Plain and keyword target_link_libraries
    signatures cannot be mixed.  Run "cmake --help-policy CMP0023" for policy
    details.  Use the cmake_policy command to set the policy and suppress this
    warning.
    The keyword signature for target_link_libraries has already been used with
    the target "qulacs".  All uses of target_link_libraries with a target
    should be either all-keyword or all-plain.
    The uses of the keyword signature are here:
     * build/temp.linux-x86_64-3.6/_deps/pybind11_fetch-src/tools/pybind11Tools.cmake:107 (target_link_libraries)
  This warning is for project developers.  Use -Wno-dev to suppress it.
  CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
  Please set them or make sure they are set and tested correctly in the CMake files:
  CUDA_cublas_device_LIBRARY (ADVANCED)
      linked by target "gpusim_shared" in directory /tmp/pip-install-sm_za7pb/qulacs-gpu/src/gpusim
      linked by target "gpusim_static" in directory /tmp/pip-install-sm_za7pb/qulacs-gpu/src/gpusim
  -- Configuring incomplete, errors occurred!
  See also "/tmp/pip-install-sm_za7pb/qulacs-gpu/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeOutput.log".
  See also "/tmp/pip-install-sm_za7pb/qulacs-gpu/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeError.log".
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-sm_za7pb/qulacs-gpu/setup.py", line 101, in <module>
      'Topic :: Communications :: Email',
    File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.6/dist-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-sm_za7pb/qulacs-gpu/setup.py", line 31, in run
      self.build_extension(ext)
    File "/tmp/pip-install-sm_za7pb/qulacs-gpu/setup.py", line 75, in build_extension
      subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
    File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-install-sm_za7pb/qulacs-gpu', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-sm_za7pb/qulacs-gpu/build/lib.linux-x86_64-3.6', '-DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/tmp/pip-install-sm_za7pb/qulacs-gpu/build/lib.linux-x86_64-3.6', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-DPYTHON_SETUP_FLAG:STR=Yes', '-DCMAKE_C_COMPILER=gcc', '-DCMAKE_CXX_COMPILER=g++', '-DCMAKE_BUILD_TYPE=Release', '-DUSE_GPU:STR=Yes']' returned non-zero exit status 1.
error
  Failed building wheel for qulacs-gpu
  Running setup.py clean for qulacs-gpu
  Running command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-sm_za7pb/qulacs-gpu/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all
  running clean
  removing 'build/temp.linux-x86_64-3.6' (and everything under it)
  'build/lib.linux-x86_64-3.6' does not exist -- can't clean it
  'build/bdist.linux-x86_64' does not exist -- can't clean it
  'build/scripts-3.6' does not exist -- can't clean it
  removing 'build'
Failed to build qulacs-gpu
Installing collected packages: qulacs-gpu
  Created temporary directory: /tmp/pip-record-n4_ej2cv
  Running setup.py install for qulacs-gpu ...     Running command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-sm_za7pb/qulacs-gpu/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-n4_ej2cv/install-record.txt --single-version-externally-managed --compile
    running install
    running build
    running build_ext
    -- The C compiler identification is GNU 7.3.0
    -- The CXX compiler identification is GNU 7.3.0
    -- Check for working C compiler: /usr/bin/gcc
    -- Check for working C compiler: /usr/bin/gcc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/g++
    -- Check for working CXX compiler: /usr/bin/g++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- USE_OMP = Yes
    -- USE_GPU = Yes
    -- USE_TEST = Yes
    -- USE_PYTHON = Yes
    -- Fetch googletest for C++ testing
    -- Found PythonInterp: /usr/bin/python3 (found version "3.6.7")
    -- Looking for pthread.h
    -- Looking for pthread.h - found
    -- Looking for pthread_create
    -- Looking for pthread_create - not found
    -- Check if compiler accepts -pthread
    -- Check if compiler accepts -pthread - yes
    -- Found Threads: TRUE
    -- Fetch pybind11 for python-binding
    -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so
    -- Performing Test HAS_CPP14_FLAG
    -- Performing Test HAS_CPP14_FLAG - Success
    -- pybind11 v2.2.4
    -- Install from pip
    -- OUTDIR = /tmp/pip-install-sm_za7pb/qulacs-gpu/build/lib.linux-x86_64-3.6
    -- CMAKE_SYSTEM_NAME = Linux
    -- CMAKE_C_COMPILER = /usr/bin/gcc
    -- CMAKE_CXX_COMPILER = /usr/bin/g++
    -- USE_OMP = Yes
    -- CMAKE_BUILD_TYPE = Release
    -- CMAKE_CXX_FLAGS = -DVERSION_INFO=\"0.1.2\" -std=gnu++11 -pthread -fext-numeric-literals -fopenmp -fPIC
    -- CMAKE_CXX_FLAGS_DEBUG = -g
    -- CMAKE_CXX_FLAGS_RELEASE = -O3 -DNDEBUG -mtune=native -march=native -mfpmath=both
    -- Found CUDA: /usr/local/cuda (found version "10.0")
    -- CUDA --
    Version: 10.0
    Library: /usr/lib/x86_64-linux-gnu/libcuda.so
    Runtime: /usr/local/cuda/lib64/libcudart.so
    Flag:
    -- Performing Test HAS_FLTO
    -- Performing Test HAS_FLTO - Success
    -- LTO enabled
    CMake Warning (dev) at python/CMakeLists.txt:58 (target_link_libraries):
      Policy CMP0023 is not set: Plain and keyword target_link_libraries
      signatures cannot be mixed.  Run "cmake --help-policy CMP0023" for policy
      details.  Use the cmake_policy command to set the policy and suppress this
      warning.
      The keyword signature for target_link_libraries has already been used with
      the target "qulacs".  All uses of target_link_libraries with a target
      should be either all-keyword or all-plain.
      The uses of the keyword signature are here:
       * build/temp.linux-x86_64-3.6/_deps/pybind11_fetch-src/tools/pybind11Tools.cmake:107 (target_link_libraries)
    This warning is for project developers.  Use -Wno-dev to suppress it.
    CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
    Please set them or make sure they are set and tested correctly in the CMake files:
    CUDA_cublas_device_LIBRARY (ADVANCED)
        linked by target "gpusim_shared" in directory /tmp/pip-install-sm_za7pb/qulacs-gpu/src/gpusim
        linked by target "gpusim_static" in directory /tmp/pip-install-sm_za7pb/qulacs-gpu/src/gpusim
    -- Configuring incomplete, errors occurred!
    See also "/tmp/pip-install-sm_za7pb/qulacs-gpu/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeOutput.log".
    See also "/tmp/pip-install-sm_za7pb/qulacs-gpu/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeError.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-sm_za7pb/qulacs-gpu/setup.py", line 101, in <module>
        'Topic :: Communications :: Email',
      File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.6/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-sm_za7pb/qulacs-gpu/setup.py", line 31, in run
        self.build_extension(ext)
      File "/tmp/pip-install-sm_za7pb/qulacs-gpu/setup.py", line 75, in build_extension
        subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
      File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-install-sm_za7pb/qulacs-gpu', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-sm_za7pb/qulacs-gpu/build/lib.linux-x86_64-3.6', '-DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/tmp/pip-install-sm_za7pb/qulacs-gpu/build/lib.linux-x86_64-3.6', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-DPYTHON_SETUP_FLAG:STR=Yes', '-DCMAKE_C_COMPILER=gcc', '-DCMAKE_CXX_COMPILER=g++', '-DCMAKE_BUILD_TYPE=Release', '-DUSE_GPU:STR=Yes']' returned non-zero exit status 1.
error
Cleaning up...
  Removing source in /tmp/pip-install-sm_za7pb/qulacs-gpu
Removed build tracker '/tmp/pip-req-tracker-s78ktjmr'
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-sm_za7pb/qulacs-gpu/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-n4_ej2cv/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-sm_za7pb/qulacs-gpu/
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/base_command.py", line 179, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/commands/install.py", line 393, in run
    use_user_site=options.use_user_site,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/req/__init__.py", line 57, in install_given_reqs
    **kwargs
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/req/req_install.py", line 945, in install
    spinner=spinner,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/utils/misc.py", line 761, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-sm_za7pb/qulacs-gpu/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-n4_ej2cv/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-sm_za7pb/qulacs-gpu/
Collapse

```

**Comment by corryvrequan** [comment]
This bug is due to changed behavior of cmake for cublas, and fixed in #120 .

**Comment by vadimoganesyan** [comment]
hi, I am unable to install qulacs-gpu on Ubuntu 22.04. I came on this thread by googling 

as far as I can tell everything is up to date...

thanks,v


.......................................
        File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'python', '--config', 'Release', '--', '-j2']' returned non-zero exit status 2.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> qulacs-gpu

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by forest1040** [comment]
@vadimoganesyan 

if you can use docker. you can build qulacs-gpu

https://github.com/qulacs/qulacs/blob/main/.devcontainer/gpu/Dockerfile

```
USE_GPU=Yes ./script/build_gcc_with_gpu.sh
USE_GPU=Yes pip install .
```
