### ISSUE TITLE
Fail to build due to C++14 feature

### ISSUE THREAD

**Issue by Roger-luo** [qulacs/qulacs#174]
I clone and run `python setup.py build` and got this error, did I miss anything?

```
/home/xluo/qulacs/build/temp.linux-x86_64-3.7/_deps/pybind11_fetch-src/include/pybind11/detail/common.h:755:19: error: static assertion failed: pybind11::overload_cast<...> requires compiling in C++14 mode
     static_assert(detail::deferred_t<std::false_type, Args...>::value,
                   ^~~~~~
/home/xluo/qulacs/python/cppsim_wrapper.cpp: In function ‘void pybind11_init_qulacs(pybind11::module&)’:
/home/xluo/qulacs/python/cppsim_wrapper.cpp:222:114: error: no matching function for call to ‘pybind11::overload_cast<const QuantumStateCpu*, const QuantumStateCpu*>::overload_cast(CPPCTYPE (*)(const QuantumState*, const QuantumState*))’
 ct", py::overload_cast<const QuantumState*, const QuantumState*>(&state::inner_product));
                                                                                       ^

In file included from /home/xluo/qulacs/build/temp.linux-x86_64-3.7/_deps/pybind11_fetch-src/include/pybind11/pytypes.h:12,
                 from /home/xluo/qulacs/build/temp.linux-x86_64-3.7/_deps/pybind11_fetch-src/include/pybind11/cast.h:13,
                 from /home/xluo/qulacs/build/temp.linux-x86_64-3.7/_deps/pybind11_fetch-src/include/pybind11/attr.h:13,
                 from /home/xluo/qulacs/build/temp.linux-x86_64-3.7/_deps/pybind11_fetch-src/include/pybind11/pybind11.h:43,
                 from /home/xluo/qulacs/python/cppsim_wrapper.cpp:2:
/home/xluo/qulacs/build/temp.linux-x86_64-3.7/_deps/pybind11_fetch-src/include/pybind11/detail/common.h:754:36: note: candidate: ‘constexpr pybind11::overload_cast<const QuantumStateCpu*, const QuantumStateCpu*>::overload_cast()’
 template <typename... Args> struct overload_cast {
                                    ^~~~~~~~~~~~~
/home/xluo/qulacs/build/temp.linux-x86_64-3.7/_deps/pybind11_fetch-src/include/pybind11/detail/common.h:754:36: note:   candidate expects 0 arguments, 1 provided
/home/xluo/qulacs/build/temp.linux-x86_64-3.7/_deps/pybind11_fetch-src/include/pybind11/detail/common.h:754:36: note: candidate: ‘constexpr pybind11::overload_cast<const QuantumStateCpu*, const QuantumStateCpu*>::overload_cast(const pybind11::overload_cast<const QuantumStateCpu*, const QuantumStateCpu*>&)’
/home/xluo/qulacs/build/temp.linux-x86_64-3.7/_deps/pybind11_fetch-src/include/pybind11/detail/common.h:754:36: note:   no known conversion for argument 1 from ‘CPPCTYPE (*)(const QuantumState*, const QuantumState*)’ {aka ‘std::complex<double> (*)(const QuantumStateCpu*, const QuantumStateCpu*)’} to ‘const pybind11::overload_cast<const QuantumStateCpu*, const QuantumStateCpu*>&’
/home/xluo/qulacs/build/temp.linux-x86_64-3.7/_deps/pybind11_fetch-src/include/pybind11/detail/common.h:754:36: note: candidate: ‘constexpr pybind11::overload_cast<const QuantumStateCpu*, const QuantumStateCpu*>::overload_cast(pybind11::overload_cast<const QuantumStateCpu*, const QuantumStateCpu*>&&)’
/home/xluo/qulacs/build/temp.linux-x86_64-3.7/_deps/pybind11_fetch-src/include/pybind11/detail/common.h:754:36: note:   no known conversion for argument 1 from ‘CPPCTYPE (*)(const QuantumState*, const QuantumState*)’ {aka ‘std::complex<double> (*)(const QuantumStateCpu*, const QuantumStateCpu*)’} to ‘pybind11::overload_cast<const QuantumStateCpu*, const QuantumStateCpu*>&&’
python/CMakeFiles/qulacs.dir/build.make:62: recipe for target 'python/CMakeFiles/qulacs.dir/cppsim_wrapper.cpp.o' failed
make[3]: *** [python/CMakeFiles/qulacs.dir/cppsim_wrapper.cpp.o] Error 1
CMakeFiles/Makefile2:996: recipe for target 'python/CMakeFiles/qulacs.dir/all' failed
make[2]: *** [python/CMakeFiles/qulacs.dir/all] Error 2
CMakeFiles/Makefile2:217: recipe for target 'CMakeFiles/python.dir/rule' failed
make[1]: *** [CMakeFiles/python.dir/rule] Error 2
Makefile:216: recipe for target 'python' failed
make: *** [python] Error 2
Traceback (most recent call last):
  File "setup.py", line 100, in <module>
    'Topic :: Communications :: Email',
  File "/home/xluo/.julia/conda/3/envs/benchmark/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/home/xluo/.julia/conda/3/envs/benchmark/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/xluo/.julia/conda/3/envs/benchmark/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/xluo/.julia/conda/3/envs/benchmark/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/xluo/.julia/conda/3/envs/benchmark/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/xluo/.julia/conda/3/envs/benchmark/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/xluo/.julia/conda/3/envs/benchmark/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 31, in run
    self.build_extension(ext)
  File "setup.py", line 75, in build_extension
    subprocess.check_call(['cmake', '--build', '.', '--target', 'python'] + build_args, cwd=self.build_temp)
  File "/home/xluo/.julia/conda/3/envs/benchmark/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'python', '--config', 'Release', '--', '-j2']' returned non-zero exit status 2.
```

CMake configuration:

```
-- USE_OMP = Yes
-- USE_GPU = No
-- USE_TEST = Yes
-- USE_PYTHON = Yes
-- Fetch googletest for C++ testing
-- Fetch pybind11 for python-binding
-- pybind11 v2.2.4
-- Install from pip
-- OUTDIR = /home/xluo/qulacs/build/lib.linux-x86_64-3.7
-- CMAKE_SYSTEM_NAME = Linux
-- CMAKE_C_COMPILER = /usr/bin/gcc
-- CMAKE_CXX_COMPILER = /usr/bin/g++
-- USE_OMP = Yes
-- CMAKE_BUILD_TYPE = Release
-- CMAKE_CXX_FLAGS = -DVERSION_INFO=\"0.1.6\" -std=gnu++11 -pthread -fext-numeric-literals -fopenmp
-- CMAKE_CXX_FLAGS_DEBUG = -g
-- CMAKE_CXX_FLAGS_RELEASE = -O3 -DNDEBUG -mtune=native -march=native -mfpmath=both
```

**Comment by corryvrequan** [comment]
Thanks for reporting this issue, @Roger-luo.

> did I miss anything?

No. This is a known bug of build script of qulacs, and this happens when qulacs is built with gcc>=9.0 and the latest pybind11. This will be resolved in the next update.

The following steps are a quick fix to this bug, which is verified in Ubuntu 18.04 and gcc-9.

1. Replace "gnu++11" in ./qulacs/CMakeLists.txt to "gnu++14".

2. Insert line "using namespace std::complex_literals;" to L15 of ./qulacs/src/cppsim/type.hpp.
Around L15 of this file becomes
```
#include <complex>
#include <Eigen/Core>
#include <Eigen/Sparse>
typedef std::complex<double> CPPCTYPE;
using namespace std::complex_literals;
typedef Eigen::VectorXcd ComplexVector;
```

3. execute "python setup.py build" again.

Please report again if you tried the above but it does not help.

**Comment by Roger-luo** [comment]
interesting, is it possible to fix it in master instead tweaking the source code?

**Comment by corryvrequan** [comment]
We plan to fix this bugs asap but please give us a time for checking the above quick fix doesn't affect our existing environments. Since others also suffer from this error, we will (probably) update new release in this weekend.

**Comment by Roger-luo** [comment]
I'll close this for now then.

**Comment by Skorkmaz88** [comment]
I get 

> complex_literals’ is not a namespace-name

error for this solution
