### ISSUE TITLE
Install issue for qulacs-gpu

### ISSUE THREAD

**Issue by beimojiguang** [qulacs/qulacs#226]
Some issue occurred when I install qulacs-gup, It seems relate to CMake and the path of gcc and g++, but I already successfully install them in my computer in Windows10, I do not know how to fix it...

Software Version:
  Platform: Window 10
  Python: 3.8.2
  pip: 20.1
  gcc: 9.2
  g++: 9.2
  CMkae: 3.17.2
  CUDA: 10.2

    Complete output (66 lines):
    running install
    running build
    running build_ext
    -- Building for: NMake Makefiles
    CMake Warning (dev) in CMakeLists.txt:
      No project() command is present.  The top-level CMakeLists.txt file must contain a literal, direct call to the project() command.  Add a line of code such as
      
      project(ProjectName)

      near the top of the file, but after cmake_minimum_required().

      CMake is pretending there is a "project(Project)" command on the first
      line.
    This warning is for project developers.  Use -Wno-dev to suppress it.

    CMake Error in CMakeLists.txt:
      Generator

        NMake Makefiles

      does not support platform specification, but platform

        x64

      was specified.

    CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
    CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
    -- Configuring incomplete, errors occurred!
    See also "C:/Users/44238/AppData/Local/Temp/pip-install-sck12o9j/qulacs-gpu/build/temp.win-amd64-3.8/Release/CMakeFiles/CMakeOutput.log".

**Comment by corryvrequan** [comment]
Thanks for being interested in qulacs.
As far as we know, for the installation of qulacs-gpu, binary must be built with Visual Studio, but cmake chooses another generator (NMake Makefiles).

After appropriate installation of CUDA, Visual studio, and CMake, the following command will show the list of generators.
> cmake --help

If "Visual Studio" which is used for the installation of CUDA is not listed, there is a problem in the installation of any of the above three. If listed, Visual Studio generator is not selected by CMake due to unknown reasons.

Probably you can force cmake to use Visual Studio generator in the installation of qulacs with the following process.
1. Clone repository with "git clone https://github.com/qulacs/qulacs"
2. Open qulacs folder and open "setup_gpu.py" with text editor.
3. Insert the following line to Line39 (https://github.com/qulacs/qulacs/blob/master/setup_gpu.py#L39).
```
cmake_args += ['-G', 'Visual Studio 16 2019 Win64']
```
4. Install qulacs-gpu with "python setup_gpu.py install".

Note that if you use visual studio 2015 or 2017, please replace 'Visual Studio 16 2019 Win64' to installed visual studio generator, such as 'Visual Studio 15 2017 Win64'

**Comment by onurdanaci** [comment]
Hi,

Is it possible to force Visual Studio installers in Linux (Ubuntu 22.04)? If not, is it possible to force gcc?

Best,
Onur

**Comment by forest1040** [comment]
@onurdanaci Try using the dev container.
https://github.com/qulacs/qulacs/tree/main/.devcontainer/cpu

**Comment by gzquse** [comment]
@forest1040 Hi ,
I am trying to deploy the qulacs-gpu in NERSC HPC but the error still occurred.
We are using shifter to pull the latest dev container and install it from scratch inside the container:

```
USE_GPU=Yes pip3 install .
Defaulting to user installation because normal site-packages is not writeable
Processing /pscratch/sd/g/gzquse/GRADIENT_IMAGE/qulacs
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.9/site-packages (from qulacs==0.6.12.dev1+g3e6056ab) (1.23.5)
Requirement already satisfied: scipy in /usr/local/lib/python3.9/site-packages (from qulacs==0.6.12.dev1+g3e6056ab) (1.10.1)
Building wheels for collected packages: qulacs
  Building wheel for qulacs (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for qulacs (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [96 lines of output]
      running bdist_wheel
      running build
      running build_py
      copying pysrc/qulacs/_version.py -> build/lib.linux-x86_64-cpython-39/qulacs
      running egg_info
      writing pysrc/qulacs.egg-info/PKG-INFO
      writing dependency_links to pysrc/qulacs.egg-info/dependency_links.txt
      writing requirements to pysrc/qulacs.egg-info/requires.txt
      writing top-level names to pysrc/qulacs.egg-info/top_level.txt
      adding license file 'LICENSE'
      writing manifest file 'pysrc/qulacs.egg-info/SOURCES.txt'
      running build_ext
      cmake: /opt/udiImage/modules/mpich/dep/libcurl.so.4: no version information available (required by cmake)
      cmake: /opt/udiImage/modules/mpich/dep/libcurl.so.4: no version information available (required by cmake)
      -- SIMD SUPPORT: No
      -- CMAKE_CXX_COMPILER_ID = GNU
      -- CMAKE_C_COMPILER_VERSION = 10.2.1
      -- CMAKE_CXX_COMPILER_VERSION = 10.2.1
      -- CMAKE_HOST_SYSTEM_PROCESSOR = unknown
      -- USE_SIMD = No
      -- USE_OMP = Yes
      -- USE_MPI = No
      -- USE_GPU = Yes
      -- USE_TEST = No
      -- COVERAGE = No
      -- USE_PYTHON = Yes
      -- OPT_FLAGS = -mtune=native -march=native
      -- Boost found at /usr/include
      -- Skip downloding googletest
      -- Fetch pybind11 for python-binding
      -- pybind11 v2.13.5
      -- Install from pip
      -- CMAKE_SYSTEM_NAME = Linux
      -- CMAKE_C_COMPILER = /usr/bin/gcc
      -- CMAKE_CXX_COMPILER = /usr/bin/g++
      -- CMAKE_BUILD_TYPE = Release
      -- CMAKE_CXX_FLAGS = -DVERSION_INFO=\"0.6.12.dev1+g3e6056ab\" -pthread -fopenmp -fPIC
      -- CMAKE_CXX_FLAGS_DEBUG = -g
      -- CMAKE_CXX_FLAGS_RELEASE = -O3 -DNDEBUG -mtune=native -march=native
      CMake Error at /usr/share/cmake-3.18/Modules/FindCUDA.cmake:716 (message):
        Specify CUDA_TOOLKIT_ROOT_DIR
      Call Stack (most recent call first):
        src/gpusim/CMakeLists.txt:42 (find_package)
      
      
      -- Configuring incomplete, errors occurred!
      See also "/pscratch/sd/g/gzquse/GRADIENT_IMAGE/qulacs/build/CMakeFiles/CMakeOutput.log".
      Traceback (most recent call last):
        File "/global/homes/g/gzquse/.local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/global/homes/g/gzquse/.local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/global/homes/g/gzquse/.local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-sm2r4349/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 438, in build_wheel
          return _build(['bdist_wheel', '--dist-info-dir', str(metadata_directory)])
        File "/tmp/pip-build-env-sm2r4349/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 426, in _build
          return self._build_with_temp_dir(
        File "/tmp/pip-build-env-sm2r4349/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 407, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-sm2r4349/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 142, in <module>
        File "/tmp/pip-build-env-sm2r4349/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-sm2r4349/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 183, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-sm2r4349/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-sm2r4349/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-sm2r4349/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 995, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-sm2r4349/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-sm2r4349/overlay/lib/python3.9/site-packages/setuptools/command/bdist_wheel.py", line 381, in run
          self.run_command("build")
        File "/tmp/pip-build-env-sm2r4349/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-sm2r4349/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 995, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-sm2r4349/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-sm2r4349/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-sm2r4349/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-sm2r4349/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 995, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-sm2r4349/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "<string>", line 39, in run
        File "<string>", line 74, in build_extension
        File "/usr/local/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '/pscratch/sd/g/gzquse/GRADIENT_IMAGE/qulacs', '-DCMAKE_ARCHIVE_OUTPUT_DIRECTORY=/pscratch/sd/g/gzquse/GRADIENT_IMAGE/qulacs/lib', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/pscratch/sd/g/gzquse/GRADIENT_IMAGE/qulacs/build/lib.linux-x86_64-cpython-39', '-DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/pscratch/sd/g/gzquse/GRADIENT_IMAGE/qulacs/bin', '-DPYTHON_EXECUTABLE=/usr/local/bin/python', '-DPYTHON_SETUP_FLAG:STR=Yes', '-DUSE_GPU:STR=No', '-DCMAKE_C_COMPILER=gcc', '-DCMAKE_CXX_COMPILER=g++', '-DCMAKE_BUILD_TYPE=Release', '-DUSE_GPU:STR=Yes']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for qulacs
Failed to build qulacs
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (qulacs)
```
