### ISSUE TITLE
Cannot load shared library on M1 macOS

### ISSUE THREAD

**Issue by ikanago** [qulacs/qulacs#431]
On M1 macOS, we cannot load qulacs shared library to run Python code.
Here is the minimal reproduction code:
```python
from qulacs import QuantumState
```
And got the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/xxx/.pyenv/versions/3.10.8/lib/python3.10/site-packages/qulacs/__init__.py", line 1, in <module>
    from qulacs_core import *
ImportError: dlopen(/Users/xxx/.pyenv/versions/3.10.8/lib/python3.10/site-packages/qulacs_core.cpython-310-darwin.so, 0x0002): tried: '/Users/xxx/.pyenv/versions/3.10.8/lib/python3.10/site-packages/qulacs_core.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))
```

**Comment by Hiroya-W** [comment]
I have the same issue on my M1 macOS...。

**Comment by ikanago** [comment]
This issue should be helpful: https://github.com/pypa/cibuildwheel/issues/1345
https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_ARCHITECTURES.html

**Comment by ikanago** [comment]
On [working branch](https://github.com/qulacs/qulacs/tree/431-cannot-load-so-M1-test), I ran cibuildwheel with the cmake variable, but I failed to build shared object for arm64 😢 
Action: https://github.com/qulacs/qulacs/actions/runs/3627423303
You can download created wheels with gh and jq command like following:
```bash
gh api \
  -H "Accept: application/vnd.github+json" \
  /repos/qulacs/qulacs/actions/artifacts | jq '.artifacts[0].archive_download_url' | xargs gh api -H "Accept: application/vnd.github+json" > artifact.zip
```
And unzip downloaded file and wheel for macOS on arm64.

**Comment by VolodyaCO** [comment]
Same issue here! @ikanago are you saying that the artifact that you want us to download has the correct wheel?

**Comment by VolodyaCO** [comment]
It's not working for me:

```zsh
$ pip install qulacs-0.1.dev1+g480e9f1-cp38-cp38-macosx_11_0_arm64.whl
Processing ./qulacs-0.1.dev1+g480e9f1-cp38-cp38-macosx_11_0_arm64.whl
Requirement already satisfied: numpy in /Users/xyz/lib/python3.8/site-packages (from qulacs==0.1.dev1+g480e9f1) (1.21.6)
Requirement already satisfied: scipy in /Users/xyz/lib/python3.8/site-packages (from qulacs==0.1.dev1+g480e9f1) (1.7.3)
Installing collected packages: qulacs
Successfully installed qulacs-0.1.dev1+g480e9f1
$ python
Python 3.8.15 | packaged by conda-forge | (default, Nov 22 2022, 08:49:06) 
[Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import qulacs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/xyz/lib/python3.8/site-packages/qulacs/__init__.py", line 1, in <module>
    from qulacs_core import *
ImportError: dlopen(/Users/xyz/lib/python3.8/site-packages/qulacs_core.cpython-38-darwin.so, 0x0002): tried: '/Users/xyz/lib/python3.8/site-packages/qulacs_core.cpython-38-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))
```

**Comment by forest1040** [comment]
Maybe we have to install the universal2 CPython version.
https://github.com/pypa/cibuildwheel/pull/1283

**Comment by VolodyaCO** [comment]
Just letting you know that I have successfully installed qulacs on my machine. Thanks!

**Comment by VolodyaCO** [comment]
Forgot to mention that this was because of #460, so https://github.com/qulacs/qulacs/issues/431#issuecomment-1338927235 worked.
