### ISSUE TITLE
Installation error on linux aarch64

### ISSUE THREAD

**Issue by ikanago** [qulacs/qulacs#499]
I cannot install qulacs==0.5.5 on linux aarch64 successfully.

## Reproduction
On Apple M1 Pro, run following
```bash
docker run -it --rm python:3.11 pip install qulacs
```

Then I got the following error.
```
  × Building wheel for qulacs (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [125 lines of output]
      /tmp/pip-build-env-iva3xw4_/overlay/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py:108: _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*.
        warnings.warn(msg, _BetaConfiguration)
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-cpython-311
      creating build/lib.linux-aarch64-cpython-311/qulacs
      copying pysrc/qulacs/__init__.py -> build/lib.linux-aarch64-cpython-311/qulacs
      copying pysrc/qulacs/_version.py -> build/lib.linux-aarch64-cpython-311/qulacs
      creating build/lib.linux-aarch64-cpython-311/qulacs/quantum_operator
      copying pysrc/qulacs/quantum_operator/__init__.py -> build/lib.linux-aarch64-cpython-311/qulacs/quantum_operator
      creating build/lib.linux-aarch64-cpython-311/qulacs/observable
      copying pysrc/qulacs/observable/_get_matrix.py -> build/lib.linux-aarch64-cpython-311/qulacs/observable
      copying pysrc/qulacs/observable/__init__.py -> build/lib.linux-aarch64-cpython-311/qulacs/observable
      creating build/lib.linux-aarch64-cpython-311/qulacs/gate
      copying pysrc/qulacs/gate/__init__.py -> build/lib.linux-aarch64-cpython-311/qulacs/gate
      creating build/lib.linux-aarch64-cpython-311/qulacs/visualizer
      copying pysrc/qulacs/visualizer/visualizer.py -> build/lib.linux-aarch64-cpython-311/qulacs/visualizer
      copying pysrc/qulacs/visualizer/__init__.py -> build/lib.linux-aarch64-cpython-311/qulacs/visualizer
      creating build/lib.linux-aarch64-cpython-311/qulacs/vistest
      copying pysrc/qulacs/vistest/__init__.py -> build/lib.linux-aarch64-cpython-311/qulacs/vistest
      copying pysrc/qulacs/vistest/test_vis.py -> build/lib.linux-aarch64-cpython-311/qulacs/vistest
      creating build/lib.linux-aarch64-cpython-311/qulacs/state
      copying pysrc/qulacs/state/__init__.py -> build/lib.linux-aarch64-cpython-311/qulacs/state
      creating build/lib.linux-aarch64-cpython-311/qulacs/circuit
      copying pysrc/qulacs/circuit/__init__.py -> build/lib.linux-aarch64-cpython-311/qulacs/circuit
      creating build/lib.linux-aarch64-cpython-311/qulacs/utils
      copying pysrc/qulacs/utils/__init__.py -> build/lib.linux-aarch64-cpython-311/qulacs/utils
      copying pysrc/qulacs/utils/conversions_openfermion.py -> build/lib.linux-aarch64-cpython-311/qulacs/utils
      creating build/lib.linux-aarch64-cpython-311/qulacs/converter
      copying pysrc/qulacs/converter/__init__.py -> build/lib.linux-aarch64-cpython-311/qulacs/converter
      copying pysrc/qulacs/converter/qasm_converter.py -> build/lib.linux-aarch64-cpython-311/qulacs/converter
      running egg_info
      writing pysrc/qulacs.egg-info/PKG-INFO
      writing dependency_links to pysrc/qulacs.egg-info/dependency_links.txt
      writing requirements to pysrc/qulacs.egg-info/requires.txt
      writing top-level names to pysrc/qulacs.egg-info/top_level.txt
      listing git files failed - pretending there aren't any
      reading manifest file 'pysrc/qulacs.egg-info/SOURCES.txt'
      adding license file 'LICENSE'
      writing manifest file 'pysrc/qulacs.egg-info/SOURCES.txt'
      copying pysrc/qulacs/__init__.pyi -> build/lib.linux-aarch64-cpython-311/qulacs
      copying pysrc/qulacs/circuit.pyi -> build/lib.linux-aarch64-cpython-311/qulacs
      copying pysrc/qulacs/gate.pyi -> build/lib.linux-aarch64-cpython-311/qulacs
      copying pysrc/qulacs/observable.pyi -> build/lib.linux-aarch64-cpython-311/qulacs
      copying pysrc/qulacs/py.typed -> build/lib.linux-aarch64-cpython-311/qulacs
      copying pysrc/qulacs/quantum_operator.pyi -> build/lib.linux-aarch64-cpython-311/qulacs
      copying pysrc/qulacs/state.pyi -> build/lib.linux-aarch64-cpython-311/qulacs
      copying pysrc/qulacs/quantum_operator/__init__.pyi -> build/lib.linux-aarch64-cpython-311/qulacs/quantum_operator
      copying pysrc/qulacs/quantum_operator/py.typed -> build/lib.linux-aarch64-cpython-311/qulacs/quantum_operator
      copying pysrc/qulacs/observable/__init__.pyi -> build/lib.linux-aarch64-cpython-311/qulacs/observable
      copying pysrc/qulacs/observable/py.typed -> build/lib.linux-aarch64-cpython-311/qulacs/observable
      copying pysrc/qulacs/gate/__init__.pyi -> build/lib.linux-aarch64-cpython-311/qulacs/gate
      copying pysrc/qulacs/gate/py.typed -> build/lib.linux-aarch64-cpython-311/qulacs/gate
      copying pysrc/qulacs/state/__init__.pyi -> build/lib.linux-aarch64-cpython-311/qulacs/state
      copying pysrc/qulacs/state/py.typed -> build/lib.linux-aarch64-cpython-311/qulacs/state
      copying pysrc/qulacs/circuit/__init__.pyi -> build/lib.linux-aarch64-cpython-311/qulacs/circuit
      copying pysrc/qulacs/circuit/py.typed -> build/lib.linux-aarch64-cpython-311/qulacs/circuit
      running build_ext
      Traceback (most recent call last):
        File "<string>", line 31, in run
        File "/usr/local/lib/python3.11/subprocess.py", line 466, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/lib/python3.11/subprocess.py", line 548, in run
          with Popen(*popenargs, **kwargs) as process:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/lib/python3.11/subprocess.py", line 1024, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/usr/local/lib/python3.11/subprocess.py", line 1901, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'cmake'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 249, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-iva3xw4_/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 413, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-iva3xw4_/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 398, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-iva3xw4_/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 133, in <module>
        File "/tmp/pip-build-env-iva3xw4_/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-iva3xw4_/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-iva3xw4_/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-iva3xw4_/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-iva3xw4_/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1213, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-iva3xw4_/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-iva3xw4_/overlay/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 325, in run
          self.run_command("build")
        File "/tmp/pip-build-env-iva3xw4_/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-iva3xw4_/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1213, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-iva3xw4_/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-iva3xw4_/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-iva3xw4_/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-iva3xw4_/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1213, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-iva3xw4_/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 33, in run
      RuntimeError: CMake must be installed to build the following extensions: qulacs_core
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for qulacs
Failed to build qulacs
ERROR: Could not build wheels for qulacs, which is required to install pyproject.toml-based projects
```

**Comment by ikanago** [comment]
It was my misunderstanding. I forgot installing cmake.
